export interface StatutoryKnowledgeChunk {
  id: string;
  actTitle: string;
  sectionOrRule: string;
  department: string;
  category: 'LEGAL_MANDATE' | 'INCENTIVE_SCHEME' | 'TECHNICAL_STANDARD' | 'PROCEDURE';
  title: string;
  officialLegaleseText: string;
  plainEnglishExplanation: string;
  actionableSteps: string[];
  keyTerms: string[];
  slaDays?: number;
  statutorySafeguard?: string;
  applicableSectors?: string[];
}

export const MAHARASHTRA_STATUTORY_CORPUS: StatutoryKnowledgeChunk[] = [
  {
    id: 'RTS_ACT_SEC_4_DEEMED',
    actTitle: 'Maharashtra Right to Services (RTS) Act, 2015',
    sectionOrRule: 'Section 4(1) & Section 4(2)',
    department: 'Maharashtra State Public Services Commission',
    category: 'LEGAL_MANDATE',
    title: 'Statutory Timelines & Deemed Approval Guarantee',
    officialLegaleseText: `Section 4(1): Every Designated Public Authority shall provide statutory public services within the specified Service Level Agreement (SLA) timeline. Section 4(2): In the event that the Designated Officer fails to issue a sanction, reject with reasoned order, or raise a structured clarification within the stipulated timeline, the application shall be deemed to have been sanctioned by operation of law, and an electronic deemed approval certificate shall be automatically generated.`,
    plainEnglishExplanation: 'Government officers in Maharashtra have a strict legal deadline to process your application. If an officer sits on your application without approving or raising a valid query before the countdown timer hits zero, Maharashtra law automatically grants you "Deemed Approval". You get an official certificate without waiting for anyone.',
    actionableSteps: [
      'Monitor your active SLA countdown timer in the ApprovalOS Dashboard.',
      'If the timer hits zero, click "Generate Deemed Approval Certificate".',
      'The electronic deemed certificate holds identical legal standing in court as an officer-signed permit.',
    ],
    keyTerms: ['deemed approval', 'rts act', 'section 4', 'sla', 'deadline', 'timer', 'automatic approval', 'delay'],
    slaDays: 30,
    statutorySafeguard: 'Legal deemed approval issued automatically under Sec 4(2) of RTS Act 2015',
  },
  {
    id: 'RTS_ACT_SEC_8_APPEALS',
    actTitle: 'Maharashtra Right to Services (RTS) Act, 2015',
    sectionOrRule: 'Section 8 & Section 9',
    department: 'Maharashtra State Public Services Commission',
    category: 'LEGAL_MANDATE',
    title: 'Grievance Escalation & Defaulting Officer Penalties',
    officialLegaleseText: `Any person whose application is not disposed of within the stipulated time limit or who is aggrieved by an arbitrary rejection may prefer a first appeal to the First Appellate Authority within thirty days. If the Designated Officer is found to have delayed the public service without reasonable cause, a penalty of ₹250 per day up to ₹5,000 shall be imposed on the defaulting officer and deducted from salary.`,
    plainEnglishExplanation: 'If an officer unfairly delays or arbitrarily rejects your file, you can file a 1-click appeal to their superior (First Appellate Authority). If the officer caused unjustified delay, the government fines them ₹250 for every single day of delay deducted directly from their paycheck.',
    actionableSteps: [
      'Go to the Grievances tab in ApprovalOS.',
      'Submit an escalation; the system automatically auto-routes it to the 1st Appellate Authority.',
      'The appellate officer has 30 days to resolve the matter and enforce compliance.',
    ],
    keyTerms: ['appeal', 'grievance', 'penalty', 'fine', 'officer delay', 'escalation', 'complaint'],
    slaDays: 30,
    statutorySafeguard: '₹250/day personal salary penalty on defaulting government officers',
  },
  {
    id: 'MIDC_DCR_RULE_14_SETBACKS',
    actTitle: 'MIDC Act 1961 & MIDC Development Control Regulations (DCR) 2009',
    sectionOrRule: 'Rule 14.1 & Rule 14.2',
    department: 'MIDC Special Planning Authority (SPA)',
    category: 'TECHNICAL_STANDARD',
    title: 'Peripheral Fire Driveway & Building Setbacks',
    officialLegaleseText: `Rule 14.1: Industrial plots exceeding 2,000 sq. meters within MIDC notified zones must maintain a mandatory minimum clear peripheral open margin of 6.0m to 12.0m along all external boundaries. For plots with hazardous or chemical operations, an unobstructed 12.0-meter reinforced concrete driveway with minimum 15.0-meter turning radius at corners is mandatory for emergency fire tender navigation under Chief Fire Officer norms.`,
    plainEnglishExplanation: 'You cannot build structures right up to your plot boundary. You must leave an open road around your factory (usually 6m to 12m wide). This driveway must be kept completely clear so fire engines can circle the building in an emergency.',
    actionableSteps: [
      'Ensure your architect designs a 12m clear peripheral corridor around all production blocks.',
      'Pre-validate your CAD drawings using MahaVault before filing to MIDC BPAMS.',
      'Keep trees, pipes, and electrical transformers outside the 12m driveway zone.',
    ],
    keyTerms: ['setback', 'driveway', 'fire lane', 'turning radius', 'margin', 'midc dcr', 'rule 14', 'building plan'],
    slaDays: 20,
    statutorySafeguard: 'Pre-check via MahaVault CAD-validator guarantees zero setbacks rejection',
  },
  {
    id: 'WATER_ACT_SEC_25_CTE',
    actTitle: 'Water (Prevention & Control of Pollution) Act 1974',
    sectionOrRule: 'Section 25 & Section 26',
    department: 'Maharashtra Pollution Control Board (MPCB)',
    category: 'LEGAL_MANDATE',
    title: 'Consent to Establish (CTE) & Zero Liquid Discharge (ZLD)',
    officialLegaleseText: `Section 25: No person shall, without the previous consent of the State Board, establish or take any steps to establish any industry, operation or process which is likely to discharge sewage or trade effluent into a stream or well or sewer or on land. The application for Consent to Establish (CTE) must contain comprehensive mass-balance flowcharts, details of Effluent Treatment Plants (ETP), and plans for Zero Liquid Discharge (ZLD) where prescribed.`,
    plainEnglishExplanation: 'You cannot start civil construction or break ground on your factory until MPCB grants a "Consent to Establish" (CTE). You must show where your wastewater goes and how you clean it. For chemical and engineering units, you must recycle 100% of your water (Zero Liquid Discharge).',
    actionableSteps: [
      'Prepare your Effluent Treatment Plant (ETP) blueprint and water mass-balance chart.',
      'Upload the schematics to MahaVault for automated engineering check.',
      'Once pre-validated, submit CTE via ApprovalOS concurrent Lane 2.',
    ],
    keyTerms: ['cte', 'consent to establish', 'mpcb', 'water act', 'pollution', 'etp', 'zld', 'wastewater', 'effluent'],
    slaDays: 30,
    statutorySafeguard: '30-day statutory SLA under Maharashtra Citizen Charter',
  },
  {
    id: 'AIR_ACT_SEC_21_CTO',
    actTitle: 'Air (Prevention & Control of Pollution) Act 1981',
    sectionOrRule: 'Section 21',
    department: 'Maharashtra Pollution Control Board (MPCB)',
    category: 'LEGAL_MANDATE',
    title: 'Consent to Operate (CTO) & Continuous Emission Monitoring',
    officialLegaleseText: `Section 21: No person operating any industrial plant in an air pollution control area shall discharge or cause or permit to be discharged the emission of any air pollutant in excess of the standards laid down by the State Board. Prior to commercial commissioning, the industrial unit must obtain Consent to Operate (CTO) and install Online Continuous Emission Monitoring Systems (OCEMS) linked directly to MPCB servers.`,
    plainEnglishExplanation: 'After building the factory but before turning on the machines for commercial production, you must get Consent to Operate (CTO). MPCB will inspect chimney heights, dust filters, and digital pollution sensors to make sure smoke and fumes comply with state limits.',
    actionableSteps: [
      'Schedule trial runs and verify chimney/stack heights against boiler capacity.',
      'Connect digital sensor telemetry to the MPCB central server.',
      'Apply for CTO 30 days before trial production completes.',
    ],
    keyTerms: ['cto', 'consent to operate', 'air act', 'stack height', 'chimney', 'emissions', 'ocems', 'pollution'],
    slaDays: 25,
    statutorySafeguard: 'Eligible for instant digital renewal based on self-certified OCEMS feeds',
  },
  {
    id: 'FACTORIES_ACT_DISH_LICENSE',
    actTitle: 'Maharashtra Factories Rules 1963 & Factories Act 1948',
    sectionOrRule: 'Rule 4 & Section 6',
    department: 'Directorate of Industrial Safety & Health (DISH) Maharashtra',
    category: 'LEGAL_MANDATE',
    title: 'Factory Plan Approval & Occupational License',
    officialLegaleseText: `Section 6 & Rule 4: No site shall be used for the location of a factory, nor shall any building in a factory be constructed, extended or taken into use as a factory, unless plans thereof have been submitted to and approved by the Chief Inspector of Factories (DISH). Applications must demonstrate emergency ventilation, minimum 14.2 cubic meters of workspace per worker, machine guarding, and occupational welfare amenities.`,
    plainEnglishExplanation: 'Before workers enter your factory, DISH must inspect and license the premises. You must guarantee safe machine spacing, adequate emergency exits, ventilation, first-aid stations, and drinking water facilities for your workforce.',
    actionableSteps: [
      'Submit factory machinery layout and ventilation diagrams.',
      'Specify expected number of male, female, and contract workers.',
      'Bundle DISH site inspection with MIDC Fire visit using our Joint Inspection Planner.',
    ],
    keyTerms: ['dish', 'factory license', 'worker safety', 'plan approval', 'occupational health', 'ventilation', 'welfare'],
    slaDays: 20,
    statutorySafeguard: 'Single-Window Joint Inspection Protocol eliminates duplicate visits',
  },
  {
    id: 'FIRE_ACT_CFO_NOC',
    actTitle: 'Maharashtra Fire Prevention & Life Safety Measures Act 2006',
    sectionOrRule: 'Section 3 & Schedule I',
    department: 'Maharashtra Fire Services / MIDC Fire Brigade',
    category: 'LEGAL_MANDATE',
    title: 'Fire Safety NOC & Hydrant Ring Main Protocol',
    officialLegaleseText: `Section 3: The owner or occupier of every building specified in the Schedule shall provide life safety and fire prevention measures as prescribed. For industrial occupancies, a dedicated static fire water storage reservoir of not less than 200,000 liters, an automated booster pump of 2,850 LPM capacity, external yard hydrants every 30 meters, and automated fire alarm sensors are mandatory prerequisites for building occupancy.`,
    plainEnglishExplanation: 'You need a Fire NOC from the Chief Fire Officer before opening. You must install a dedicated water tank for firefighting (usually 100,000 to 200,000 liters), fire hoses every 30 meters, emergency sprinklers, and emergency alarm buttons.',
    actionableSteps: [
      'Design fire hydrant network with 150mm diameter MS ring main pipes.',
      'Install an underground water storage tank dedicated solely to firefighting.',
      'Submit fire safety plan in parallel with MIDC Building Plan in Lane 3.',
    ],
    keyTerms: ['fire noc', 'cfo', 'hydrant', 'sprinkler', 'static tank', 'fire brigade', 'safety measures'],
    slaDays: 21,
    statutorySafeguard: 'Runs in parallel with Architectural Building Plan, saving 3 weeks',
  },
  {
    id: 'ELECTRICITY_ACT_HT_POWER',
    actTitle: 'Electricity Act 2003 & MERC Supply Code Regulations',
    sectionOrRule: 'Regulation 4.1',
    department: 'Maharashtra State Electricity Distribution Co. (MSEDCL)',
    category: 'PROCEDURE',
    title: 'High Tension (HT 11kV/33kV) Industrial Power Release',
    officialLegaleseText: `Regulation 4.1: Industrial consumers demanding load above 100 kVA must be supplied at High Tension (HT) voltage levels (11kV, 22kV or 33kV). Technical feasibility studies shall evaluate distance to nearest 33/11kV substation, spare transformer capacity, and require dedicated Express Feeder bays where load exceeds 1,500 kVA.`,
    plainEnglishExplanation: 'Small factories run on standard power, but industrial manufacturing requires High Tension (HT) electricity. MSEDCL must check whether the local electrical substation has enough spare capacity. If you need a lot of power, they may run a dedicated direct line from the substation to your factory.',
    actionableSteps: [
      'Calculate your total connected load (kVA) and maximum demand.',
      'File power feasibility concurrently on Day 18 after Land Allotment.',
      'ApprovalOS utilizes 18-day float/slack on power so substation studies never delay construction.',
    ],
    keyTerms: ['power', 'msedcl', 'ht power', 'transformer', 'substation', 'feeder', 'load sanction', 'electricity'],
    slaDays: 25,
    statutorySafeguard: '18 days of calculated slack absorbs power grid study delays',
  },
  {
    id: 'IBR_BOILER_REGISTRATION',
    actTitle: 'Indian Boiler Regulations (IBR), 1950',
    sectionOrRule: 'Regulation 375 & 392',
    department: 'Directorate of Steam Boilers, Maharashtra',
    category: 'TECHNICAL_STANDARD',
    title: 'High-Pressure Steam Boiler Hydraulic Testing & Commissioning',
    officialLegaleseText: `Regulation 375: Prior to commissioning any steam boiler having capacity exceeding 25 liters and design pressure exceeding 1 kg/cm², the boiler shall be subject to hydraulic proof test at 1.5 times the maximum allowable working pressure by an Inspector of Boilers. Steam pipelines must be certified by radiographic inspection of weld joints.`,
    plainEnglishExplanation: 'If your factory uses steam for heating or power generation, the boiler must undergo a high-pressure water test (hydraulic test) overseen by a government boiler inspector. This prevents catastrophic steam explosion risks.',
    actionableSteps: [
      'Purchase IBR-certified boilers with Form II manufacturer test certificates.',
      'Schedule hydraulic testing 20 days prior to steam commissioning.',
      'Submit steam piping layout drawings signed by an approved chartered engineer.',
    ],
    keyTerms: ['boiler', 'steam', 'hydraulic test', 'ibr', 'directorate of boilers', 'pressure', 'pipeline'],
    slaDays: 15,
    statutorySafeguard: 'Auto-synchronized with CTO timeline for seamless steam commissioning',
  },
  {
    id: 'MAHA_PSI_2019_INCENTIVES',
    actTitle: 'Maharashtra Package Scheme of Incentives (PSI 2019/2024)',
    sectionOrRule: 'Resolution No. PSI-2019/CR-46/IND-8',
    department: 'Directorate of Industries, Govt of Maharashtra',
    category: 'INCENTIVE_SCHEME',
    title: 'Industrial Promotion Subsidy (IPS) on State GST',
    officialLegaleseText: `Under the Package Scheme of Incentives (PSI 2019), manufacturing enterprises investing in developing talukas (Categories B, C, D, and D+) are eligible for Industrial Promotion Subsidy (IPS) ranging from 60% to 100% of eligible gross capital investment, disbursed annually as a refund of Net State GST (SGST) paid for a period of 7 to 10 years.`,
    plainEnglishExplanation: 'The Maharashtra Government will refund up to 100% of the State GST (SGST) your factory pays on sales for 7 to 10 years. For a ₹20 Crore investment in areas like Chakan, Pune, or Aurangabad, this can return up to ₹12-16 Crores back to your business.',
    actionableSteps: [
      'Register for PSI 2019 Eligibility Certificate before commercial production starts.',
      'File monthly SGST returns to create the audit trail for subsidy disbursement.',
      'Check eligible taluka category in the ApprovalOS Incentives Tab.',
    ],
    keyTerms: ['psi 2019', 'ips', 'subsidy', 'sgst', 'incentives', 'package scheme', 'refund', 'gst reimbursement'],
    statutorySafeguard: 'Guaranteed financial subsidy sanctioned under State Cabinet Policy',
  },
  {
    id: 'STAMP_DUTY_EXEMPTION_BOMBAY',
    actTitle: 'Bombay Stamp Act 1958',
    sectionOrRule: 'Section 9(a) Notification',
    department: 'Revenue & Forest Department / Directorate of Industries',
    category: 'INCENTIVE_SCHEME',
    title: '100% Stamp Duty Waiver on MIDC Industrial Leases',
    officialLegaleseText: `In exercise of powers conferred by clause (a) of Section 9 of the Maharashtra Stamp Act, the Government of Maharashtra grants 100% exemption from payment of stamp duty chargeable on instruments of lease deed, mortgage deed, and loan agreements executed by eligible industrial enterprises situated in notified MIDC industrial areas and SEZs.`,
    plainEnglishExplanation: 'You do not have to pay the standard 5%-7% stamp duty when signing your land lease deed with MIDC or mortgaging your property for bank loans. This saves an entrepreneur ₹10 to ₹50 Lakhs upfront.',
    actionableSteps: [
      'Obtain Stamp Duty Exemption Certificate from District Industries Centre (DIC).',
      'Present the certificate at the Sub-Registrar Office during deed registration.',
      'Zero payment required on MIDC industrial lease documents.',
    ],
    keyTerms: ['stamp duty', 'exemption', 'waiver', 'lease deed', 'registration', 'bombay stamp act', 'dic'],
    statutorySafeguard: 'Zero upfront stamp duty payment required upon presenting DIC certificate',
  },
  {
    id: 'ELECTRICITY_DUTY_EXEMPTION',
    actTitle: 'Maharashtra Electricity Duty Act, 2016',
    sectionOrRule: 'Section 3(2) Exemption Schedule',
    department: 'Energy Department, Govt of Maharashtra',
    category: 'INCENTIVE_SCHEME',
    title: '7 to 10 Years Complete Electricity Duty Waiver',
    officialLegaleseText: `Eligible new manufacturing units registered under the Package Scheme of Incentives (PSI) shall be exempt from the levy and payment of electricity duty under the Maharashtra Electricity Duty Act for a period of 7 years in Category B & C areas and 10 years in Category D & D+ areas from the date of commencement of commercial production.`,
    plainEnglishExplanation: 'Industrial electricity bills in Maharashtra include a state electricity duty (up to 9.3%). Eligible new factories receive a complete 100% waiver on this duty for 7 to 10 years, cutting your monthly power bills significantly.',
    actionableSteps: [
      'Submit PSI Eligibility Certificate to your local MSEDCL billing circle office.',
      'The electricity duty line item on your monthly power invoice will be credited to ₹0.',
    ],
    keyTerms: ['electricity duty', 'power bill waiver', 'energy department', 'psi', 'electricity duty exemption'],
    statutorySafeguard: 'Duty line item deducted automatically from MSEDCL monthly bill',
  },
  {
    id: 'CMEGP_MSME_SCHEME',
    actTitle: 'Chief Minister Employment Generation Programme (CMEGP)',
    sectionOrRule: 'Industries Dept GR 2019/CMEGP/CR-88',
    department: 'Directorate of Industries & Maharashtra State Innovation Society (MSIS)',
    category: 'INCENTIVE_SCHEME',
    title: 'Capital Subsidy & 5% Interest Subvention for MSMEs & Startups',
    officialLegaleseText: `Under CMEGP, first-generation entrepreneurs and MSME manufacturing projects up to ₹50 Lakhs (and micro-units up to ₹1 Crore) receive a non-repayable capital subsidy of 15% to 35% of total project cost (higher slab for women, SC/ST, and rural units), alongside 5% annual interest subvention on term loans for 5 years.`,
    plainEnglishExplanation: 'For startups and first-generation MSME founders, the Chief Minister scheme provides a free, non-repayable cash grant of up to 35% of your total project setup cost, plus pays 5% of your bank loan interest for 5 years.',
    actionableSteps: [
      'Apply online via ApprovalOS with Udyam Registration and Project DPR.',
      'District Taskforce Committee reviews and sanctions subsidy within 21 days.',
      'Subsidy credited directly into your bank loan account as back-ended capital grant.',
    ],
    keyTerms: ['cmegp', 'startup subsidy', 'msme grant', 'interest subvention', 'first generation', 'women entrepreneur'],
    statutorySafeguard: 'Direct bank account credit backed by Maharashtra State Innovation Society',
  },
  {
    id: 'GREEN_CHANNEL_SELF_CERT',
    actTitle: 'Maharashtra Right to Services & MIDC Circular 2020',
    sectionOrRule: 'Circular No. MIDC/CP/2020/Auto-101',
    department: 'MIDC & MPCB Joint Taskforce',
    category: 'PROCEDURE',
    title: 'Green Channel Express Fast-Track (48-Day Journey)',
    officialLegaleseText: `Manufacturing projects categorized under White or Green pollution tiers, or situated inside notified MIDC industrial parks with pre-notified generic Environmental Impact Assessments, shall be eligible for Green Channel fast-tracking. Routine desk scrutinies are substituted with DigiLocker-authenticated self-declarations, enabling instant deemed sanctions within 48 hours under Section 4(1) of RTS Act 2015.`,
    plainEnglishExplanation: 'If you produce non-polluting goods (White/Green category) or set up inside a government MIDC industrial park, you skip the physical queue. You upload verified digital declarations via DigiLocker and receive instant deemed clearance, shrinking your launch time to just 48 days.',
    actionableSteps: [
      'Verify that your manufacturing process produces zero toxic effluent.',
      'Maintain an ApprovalOS Promoter Trust Score ≥ 80.',
      'Receive instant auto-sanction certificates under Green Channel.',
    ],
    keyTerms: ['green channel', 'fast track', 'self certification', 'digilocker', 'white category', 'clean tech', 'deemed'],
    slaDays: 7,
    statutorySafeguard: 'Instant legal deemed approval issued within 48 hours',
  },
  {
    id: 'MAHAVAULT_PRE_VALIDATION',
    actTitle: 'MahaVault Intelligent Data Reuse & Pre-Validation Engine',
    sectionOrRule: 'ApprovalOS Enterprise Standard',
    department: 'Multi-Department Integrated Gateway (MAITRI)',
    category: 'TECHNICAL_STANDARD',
    title: 'Zero-Query Pre-Validation & Single-Submission Data Reuse',
    officialLegaleseText: `MahaVault integrates automated rule-based CAD drawing parsing, chemical mass-balance consistency audits, and DigiLocker KYC deduplication. By analyzing submissions against 48 statutory criteria prior to departmental transmission, MahaVault eliminates incomplete applications, preventing the 78% query loop historically encountered by applicants across MIDC, MPCB, and DISH.`,
    plainEnglishExplanation: 'Instead of uploading the same PAN, GST, and land papers 5 times to 5 different departments, you upload them once to MahaVault. Our engine checks your engineering drawings for errors *before* any government officer sees them, guaranteeing zero document query rejections.',
    actionableSteps: [
      'Upload architectural drawings, land deeds, and company records once.',
      'Watch MahaVault run 48 automatic compliance checks.',
      'Documents are automatically dispatched to MIDC, MPCB, and DISH simultaneously.',
    ],
    keyTerms: ['mahavault', 'pre-validation', 'zero query', 'data reuse', 'cad scrutiny', 'digilocker', 'document check'],
    statutorySafeguard: 'Eliminates 78% of departmental query loops and delays',
  },
];
