import { BusinessProfile } from '@approvalos/shared';

export const DEMO_PROFILES: Record<string, BusinessProfile> = {
  EV_PUNE: {
    id: 'demo_profile_ev_pune',
    companyName: 'Aegis Lithium Mobility Pvt Ltd',
    sector: 'EV_MANUFACTURING',
    state: 'MAHARASHTRA',
    district: 'Pune (Chakan MIDC Phase IV)',
    landType: 'GOVT_INDUSTRIAL_PARK',
    landAreaAcres: 25,
    builtUpAreaSqMeters: 45000,
    investmentInrCr: 120,
    powerRequiredKva: 3500,
    waterRequiredKld: 150,
    expectedEmployees: 450,
    pollutionCategory: 'ORANGE',
    isMsme: false,
    hazardousChemicals: false,
    boilerInstalled: false,
    effluentDischarge: true,
    promoterExperienceYears: 12,
    pastComplianceRecord: 'EXEMPLARY',
    trustScore: 88,
  },
  PHARMA_AURANGABAD: {
    id: 'demo_profile_pharma_aurangabad',
    companyName: 'Vanguard Biopharma Life Sciences Ltd',
    sector: 'PHARMA',
    state: 'MAHARASHTRA',
    district: 'Chhatrapati Sambhajinagar (Shendra MIDC / AURIC DMIC)',
    landType: 'PRIVATE_AGRICULTURAL',
    landAreaAcres: 15,
    builtUpAreaSqMeters: 28000,
    investmentInrCr: 85,
    powerRequiredKva: 2200,
    waterRequiredKld: 320,
    expectedEmployees: 220,
    pollutionCategory: 'RED',
    isMsme: false,
    hazardousChemicals: true,
    boilerInstalled: true,
    effluentDischarge: true,
    promoterExperienceYears: 8,
    pastComplianceRecord: 'CLEAN',
    trustScore: 72,
  },
  SOLAR_NAGPUR: {
    id: 'demo_profile_solar_nagpur',
    companyName: 'Helios Photovoltaics Tech India Pvt Ltd',
    sector: 'RENEWABLE_ENERGY',
    state: 'MAHARASHTRA',
    district: 'Nagpur (MIHAN SEZ / Butibori MIDC)',
    landType: 'SEZ',
    landAreaAcres: 10,
    builtUpAreaSqMeters: 18000,
    investmentInrCr: 45,
    powerRequiredKva: 1200,
    waterRequiredKld: 40,
    expectedEmployees: 160,
    pollutionCategory: 'WHITE',
    isMsme: true,
    hazardousChemicals: false,
    boilerInstalled: false,
    effluentDischarge: false,
    promoterExperienceYears: 6,
    pastComplianceRecord: 'EXEMPLARY',
    trustScore: 94,
  },
  FOOD_NASHIK: {
    id: 'demo_profile_food_nashik',
    companyName: 'Godavari Valley Agro Foods Ltd',
    sector: 'FOOD_PROCESSING',
    state: 'MAHARASHTRA',
    district: 'Nashik (Dindori Mega Food Park / MIDC)',
    landType: 'GOVT_INDUSTRIAL_PARK',
    landAreaAcres: 8,
    builtUpAreaSqMeters: 12000,
    investmentInrCr: 22,
    powerRequiredKva: 800,
    waterRequiredKld: 90,
    expectedEmployees: 95,
    pollutionCategory: 'GREEN',
    isMsme: true,
    hazardousChemicals: false,
    boilerInstalled: true,
    effluentDischarge: true,
    promoterExperienceYears: 5,
    pastComplianceRecord: 'NEW_ENTRANT',
    trustScore: 80,
  },
};

// Aliases for graceful fallback
DEMO_PROFILES.EV_GUJARAT = DEMO_PROFILES.EV_PUNE;
DEMO_PROFILES.PHARMA_MAHARASHTRA = DEMO_PROFILES.PHARMA_AURANGABAD;
DEMO_PROFILES.SOLAR_TAMIL_NADU = DEMO_PROFILES.SOLAR_NAGPUR;
DEMO_PROFILES.FOOD_UP = DEMO_PROFILES.FOOD_NASHIK;
